-- Товары: подкатегория «Проволока вязальная» (supplies-wire).
-- Перед запуском: supabase-seed-supplies-subcategories.sql.
-- Бухты: sale_unit «боб», length_m и meters_per_sale_unit — метраж бухты.

insert into public.products (
  slug,
  category_id,
  subcategory_id,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  sale_unit,
  weight_kg,
  price_per_ton,
  price_per_unit,
  price_per_meter,
  meters_per_sale_unit,
  stock,
  popular,
  article,
  card_title,
  image,
  sort_order,
  is_published,
  updated_at
)
select
  v.slug,
  c.id,
  'supplies-wire',
  v.name,
  v.size,
  v.dimension,
  v.steel,
  v.gost,
  v.length_m,
  v.sale_unit,
  v.weight_kg,
  null,
  v.price_per_unit,
  null,
  v.meters_per_sale_unit,
  v.stock,
  false,
  v.article,
  v.card_title,
  '/products/supplies.webp',
  v.sort_order,
  true,
  now()
from public.categories c
cross join (
  values
    (
      'soputstvuyushchie-art-14254',
      'Проволока стальная низкоугл. оцинкованная Ø3,0 мм (бухта 50 м), РФ',
      'Ø3,0 мм, бухта 50 м',
      3::numeric,
      'оцинкованная',
      'ГОСТ 3282-74',
      50::numeric,
      'боб',
      2.8::numeric,
      18::numeric,
      50::numeric,
      'in',
      '14254',
      'Проволока оц. Ø3,0, бухта 50 м',
      1
    ),
    (
      'soputstvuyushchie-art-16667',
      'Проволока оцинкованная вязальная 5,0 мм (бухта 7,7 кг — 50 м), РФ',
      'Ø5,0 мм, бухта 50 м',
      5::numeric,
      'оцинкованная',
      'ГОСТ 3282-74',
      50::numeric,
      'боб',
      7.7::numeric,
      53::numeric,
      50::numeric,
      'in',
      '16667',
      'Проволока вяз. Ø5,0, 7,7 кг / 50 м',
      2
    ),
    (
      'soputstvuyushchie-art-16423',
      'Проволока оцинкованная вязальная 2,0 мм (бухта 2,47 кг — 100 м), РФ',
      'Ø2,0 мм, бухта 100 м',
      2::numeric,
      'оцинкованная',
      'ГОСТ 3282-74',
      100::numeric,
      'боб',
      2.47::numeric,
      12::numeric,
      100::numeric,
      'in',
      '16423',
      'Проволока вяз. Ø2,0, 100 м',
      3
    ),
    (
      'soputstvuyushchie-art-17086',
      'Проволока ТО оцинк. KRONEX, 4,0 мм',
      'Ø4,0 мм',
      4::numeric,
      'оцинкованная',
      'ТУ производителя',
      null::numeric,
      'шт',
      5::numeric,
      null::numeric,
      null::numeric,
      'out',
      '17086',
      'Проволока KRONEX Ø4,0',
      4
    ),
    (
      'soputstvuyushchie-art-16654',
      'Проволока оцинкованная вязальная 1,2 мм (бухта 1 кг), РФ',
      'Ø1,2 мм, бухта 1 кг',
      1.2::numeric,
      'оцинкованная',
      'ГОСТ 3282-74',
      null::numeric,
      'шт',
      1::numeric,
      null::numeric,
      null::numeric,
      'out',
      '16654',
      'Проволока вяз. Ø1,2, 1 кг',
      5
    ),
    (
      'soputstvuyushchie-art-16292',
      'Заготовка из проволоки ОЦИНК., d/1,2 т/о, бухта 100 м.п., РБ',
      'Ø1,2 мм, бухта 100 м',
      1.2::numeric,
      'оцинкованная',
      'ТУ производителя',
      100::numeric,
      'боб',
      1.1::numeric,
      12::numeric,
      100::numeric,
      'in',
      '16292',
      'Проволока оц. Ø1,2, бухта 100 м, РБ',
      6
    )
) as v(
  slug,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  sale_unit,
  weight_kg,
  price_per_unit,
  meters_per_sale_unit,
  stock,
  article,
  card_title,
  sort_order
)
where c.slug = 'soputstvuyushchie-tovary'
on conflict (slug) do update set
  category_id = excluded.category_id,
  subcategory_id = excluded.subcategory_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  gost = excluded.gost,
  length_m = excluded.length_m,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_unit = excluded.price_per_unit,
  meters_per_sale_unit = excluded.meters_per_sale_unit,
  stock = excluded.stock,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
