-- Категория «Арматура гладкая» и 7 позиций как на витрине-референсе.
-- Перед запуском: supabase-schema.sql, supabase-admin-rpc.sql
-- Картинка категории: public/products/rebar-catalog/armatura-gladkaya.png

delete from public.products where slug like 'armatura-gladkaya-%' and slug not like '%-art-%';

insert into public.categories (
  id, slug, name, menu_name, tagline, description, image, sort_order,
  dimension_label, seo_title, seo_description, is_published, updated_at
) values (
  'rebar-smooth',
  'armatura-gladkaya',
  'Арматура гладкая',
  'Арматура гладкая',
  'А240, круг — в наличии и под заказ',
  'Гладкая горячекатаная арматура и круглый прокат для хомутов, распределительной сетки и монтажных элементов. Цена за тонну, резка в размер.',
  '/products/rebar-catalog/armatura-gladkaya.png',
  2,
  'Диаметр',
  'Арматура гладкая — купить в Минске и Борисове | Ромедов',
  'Арматура гладкая А240 и круглый прокат, цена за тонну, наличие на складе.',
  true,
  now()
)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  menu_name = excluded.menu_name,
  tagline = excluded.tagline,
  description = excluded.description,
  image = excluded.image,
  sort_order = excluded.sort_order,
  dimension_label = excluded.dimension_label,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  is_published = excluded.is_published,
  updated_at = now();

insert into public.products (
  slug, category_id, name, size, dimension, steel, gost, length_m, sale_unit,
  weight_kg, price_per_ton, price_per_unit, price_per_meter, meters_per_sale_unit,
  stock, popular, article, card_title, image, is_published, updated_at
) values
(
  'armatura-gladkaya-art-10388',
  'rebar-smooth',
  'Арматура гладкая А240 (класс А1) ф. 10 мм Россия',
  'Ø10 мм',
  10,
  'А240 (А1)',
  'ГОСТ 34028-2016',
  11.7,
  'м',
  0.617,
  2317.5,
  null, null, null,
  'in', false, '10388',
  'Арматура гладкая А240 (класс А1) ф. 10 мм Россия',
  null,
  true, now()
),
(
  'armatura-gladkaya-art-08583',
  'rebar-smooth',
  'Круг Ст3 12 мм ГОСТ 2590-2006',
  'Ø12 мм',
  12,
  'Ст3',
  'ГОСТ 2590-2006',
  6,
  'м',
  0.888,
  2472,
  null, null, null,
  'in', false, '08583',
  'Круг Ст3 12мм Гост 2590-2006',
  null,
  true, now()
),
(
  'armatura-gladkaya-art-08729',
  'rebar-smooth',
  'Арматура гладкая 8,0 Ст1сп ГОСТ 3282-74 РБ',
  'Ø8 мм',
  8,
  'Ст1сп',
  'ГОСТ 3282-74',
  11.7,
  'м',
  0.395,
  3450,
  null, null, null,
  'in', false, '08729',
  'Арматура гладкая 8,0 Ст1сп Гост 3282-74 РБ',
  null,
  true, now()
),
(
  'armatura-gladkaya-art-11533',
  'rebar-smooth',
  'Круг 10,0 Ст1сп ГОСТ 3282-74',
  'Ø10 мм',
  10,
  'Ст1сп',
  'ГОСТ 3282-74',
  11.7,
  'м',
  0.617,
  null,
  null, null, null,
  'order', false, '11533',
  'Круг 10,0 Ст1сп ГОСТ 3282-74',
  null,
  true, now()
),
(
  'armatura-gladkaya-art-10510',
  'rebar-smooth',
  'Арматура гладкая 6,0 Ст1сп ГОСТ 3282-74',
  'Ø6 мм',
  6,
  'Ст1сп',
  'ГОСТ 3282-74',
  11.7,
  'м',
  0.222,
  2626.5,
  null, null, null,
  'in', false, '10510',
  'Арматура гладкая 6,0 Ст1сп Гост 3282-74',
  null,
  true, now()
),
(
  'armatura-gladkaya-art-12420',
  'rebar-smooth',
  'Арматура гладкая А240 (класс А1) ф. 25 мм РБ',
  'Ø25 мм',
  25,
  'А240 (А1)',
  'ГОСТ 34028-2016',
  11.7,
  'м',
  3.853,
  2317.5,
  null, null, null,
  'in', false, '12420',
  'Арматура гладкая А240 (класс А1) ф. 25 мм РБ',
  null,
  true, now()
),
(
  'armatura-gladkaya-art-09228',
  'rebar-smooth',
  'Арматурный прокат 16 А-1 11,7 м (круг гладкий)',
  'Ø16 мм',
  16,
  'А240 (А1)',
  'ГОСТ 34028-2016',
  11.7,
  'м',
  1.578,
  3450,
  null, null, null,
  'in', false, '09228',
  'Арматурный прокат 16 А-1 11,7м (КРУГ ГЛАДКИЙ)',
  null,
  true, now()
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  gost = excluded.gost,
  length_m = excluded.length_m,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_ton = excluded.price_per_ton,
  price_per_unit = excluded.price_per_unit,
  price_per_meter = excluded.price_per_meter,
  meters_per_sale_unit = excluded.meters_per_sale_unit,
  stock = excluded.stock,
  popular = excluded.popular,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  is_published = excluded.is_published,
  updated_at = now();
