-- Товары: подкатегория «Трубы оцинкованные ВГП и электросварные» (pipe-zn).
-- Перед запуском: supabase-seed-pipe-subcategories.sql.

insert into public.products (
  slug,
  category_id,
  subcategory_id,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  sale_unit,
  weight_kg,
  price_per_ton,
  price_per_unit,
  price_per_meter,
  meters_per_sale_unit,
  stock,
  popular,
  article,
  card_title,
  image,
  sort_order,
  is_published,
  updated_at
)
select
  v.slug,
  c.id,
  'pipe-zn',
  v.name,
  v.size,
  v.dimension,
  'оцинкованная',
  v.gost,
  6::numeric,
  'м',
  v.weight_kg,
  v.price_per_ton,
  null,
  null,
  null,
  v.stock,
  false,
  v.article,
  v.card_title,
  '/products/pipe.webp',
  v.sort_order,
  true,
  now()
from public.categories c
cross join (
  values
    (
      'truby-stalnye-zn-art-04518',
      'Труба ВГП оцинкованная Ду 25×3,2 ГОСТ 3262-75',
      'Ду 25×3,2 мм',
      25::numeric,
      'ГОСТ 3262-75',
      2.33::numeric,
      null::numeric,
      'out',
      '04518',
      'Труба ВГП оц. Ду 25×3,2',
      1
    ),
    (
      'truby-stalnye-zn-art-04732',
      'Труба электросварная оцинкованная 76×3,5 мм ГОСТ 10704-91',
      '76×3,5 мм',
      76::numeric,
      'ГОСТ 10704-91',
      6.26::numeric,
      4230::numeric,
      'in',
      '04732',
      'Труба э/с оц. 76×3,5',
      2
    ),
    (
      'truby-stalnye-zn-art-04731',
      'Труба ВГП оцинкованная Ду 40×3,5 ГОСТ 3262-75',
      'Ду 40×3,5 мм',
      40::numeric,
      'ГОСТ 3262-75',
      3.55::numeric,
      5770::numeric,
      'in',
      '04731',
      'Труба ВГП оц. Ду 40×3,5',
      3
    ),
    (
      'truby-stalnye-zn-art-04527',
      'Труба ВГП оцинкованная Ду 15×2,8 ГОСТ 3262-75',
      'Ду 15×2,8 мм',
      15::numeric,
      'ГОСТ 3262-75',
      1.28::numeric,
      4732.03::numeric,
      'in',
      '04527',
      'Труба ВГП оц. Ду 15×2,8',
      4
    ),
    (
      'truby-stalnye-zn-art-04519',
      'Труба ВГП оцинкованная Ду 32×3,2 ГОСТ 3262-75',
      'Ду 32×3,2 мм',
      32::numeric,
      'ГОСТ 3262-75',
      2.9::numeric,
      4430::numeric,
      'in',
      '04519',
      'Труба ВГП оц. Ду 32×3,2',
      5
    ),
    (
      'truby-stalnye-zn-art-04517',
      'Труба ВГП оцинкованная Ду 20×2,8 ГОСТ 3262-75',
      'Ду 20×2,8 мм',
      20::numeric,
      'ГОСТ 3262-75',
      1.63::numeric,
      4573.2::numeric,
      'in',
      '04517',
      'Труба ВГП оц. Ду 20×2,8',
      6
    ),
    (
      'truby-stalnye-zn-art-04402',
      'Труба ВГП оцинкованная Ду 50×3,5 ГОСТ 3262-75',
      'Ду 50×3,5 мм',
      50::numeric,
      'ГОСТ 3262-75',
      4.88::numeric,
      4950::numeric,
      'in',
      '04402',
      'Труба ВГП оц. Ду 50×3,5',
      7
    ),
    (
      'truby-stalnye-zn-art-08775',
      'Труба электросварная оцинкованная Ду 89×3,5 мм ГОСТ 10705-80',
      '89×3,5 мм',
      89::numeric,
      'ГОСТ 10705-80',
      7.38::numeric,
      4170::numeric,
      'in',
      '08775',
      'Труба э/с оц. 89×3,5',
      8
    ),
    (
      'truby-stalnye-zn-art-08774',
      'Труба электросварная оцинкованная Ду 108×3,5 мм ГОСТ 10704-91',
      '108×3,5 мм',
      108::numeric,
      'ГОСТ 10704-91',
      9.03::numeric,
      4480::numeric,
      'in',
      '08774',
      'Труба э/с оц. 108×3,5',
      9
    )
) as v(
  slug,
  name,
  size,
  dimension,
  gost,
  weight_kg,
  price_per_ton,
  stock,
  article,
  card_title,
  sort_order
)
where c.slug = 'truby-stalnye'
on conflict (slug) do update set
  category_id = excluded.category_id,
  subcategory_id = excluded.subcategory_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  gost = excluded.gost,
  length_m = excluded.length_m,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_ton = excluded.price_per_ton,
  stock = excluded.stock,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
