-- Товар: подкатегория «Сетка сварная d 5 мм» (mesh-d5).
-- Перед запуском: supabase-seed-mesh-subcategories.sql.

insert into public.products (
  slug,
  category_id,
  subcategory_id,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  sale_unit,
  weight_kg,
  price_per_ton,
  price_per_unit,
  price_per_meter,
  meters_per_sale_unit,
  stock,
  popular,
  article,
  card_title,
  image,
  sort_order,
  is_published,
  updated_at
)
select
  'setka-armiruyushchaya-art-08756',
  c.id,
  'mesh-d5',
  'Сетка арматурная сварная С500 d5,0 мм, ячейка 100×100 мм, лист 1000×2000 мм, ГОСТ 23279',
  '100×100 мм, лист 1000×2000 мм',
  100::numeric,
  'С500',
  'ГОСТ 23279-2012',
  null,
  'карта',
  6.8::numeric,
  3530::numeric,
  null,
  null,
  null,
  'in',
  false,
  '08756',
  'Сетка С500 d5, 100×100, лист 1000×2000',
  '/products/mesh.webp',
  1,
  true,
  now()
from public.categories c
where c.slug = 'setka-armiruyushchaya'
on conflict (slug) do update set
  category_id = excluded.category_id,
  subcategory_id = excluded.subcategory_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  gost = excluded.gost,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_ton = excluded.price_per_ton,
  stock = excluded.stock,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
