-- Категория «Уголок стальной» + 10 товаров (референс витрины).
-- Перед запуском: supabase-schema.sql, supabase-admin-rpc.sql.
-- weight_kg — масса 1 п.м. (7850 кг/м³, площадь сечения 2×a×t − t²).

insert into public.categories (
  id, slug, name, menu_name, tagline, description, image, sort_order,
  dimension_label, seo_title, seo_description, is_published, updated_at
) values (
  'angle',
  'ugolok-stalnoy',
  'Уголок стальной',
  'Уголок стальной',
  'Равнополочный 25–100 мм',
  'Горячекатаный равнополочный уголок по ГОСТ 8509-93 для рам, обвязок, закладных и усиления конструкций. Мерная длина 6 и 12 м.',
  '/products/angle.webp',
  6,
  'Полка',
  'Уголок стальной равнополочный — цена за тонну и метр | Ромедов',
  'Уголок стальной равнополочный 25×25 — 100×100 мм по ГОСТ 8509-93. Продажа тоннами и метрами, резка в размер, доставка по Беларуси.',
  true,
  now()
)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  menu_name = excluded.menu_name,
  tagline = excluded.tagline,
  description = excluded.description,
  image = excluded.image,
  sort_order = excluded.sort_order,
  dimension_label = excluded.dimension_label,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  is_published = true,
  updated_at = now();

insert into public.products (
  slug,
  category_id,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  sale_unit,
  weight_kg,
  price_per_ton,
  price_per_unit,
  price_per_meter,
  meters_per_sale_unit,
  stock,
  popular,
  article,
  card_title,
  image,
  sort_order,
  is_published,
  updated_at
)
select
  v.slug,
  'angle',
  v.name,
  v.size,
  v.dimension,
  v.steel,
  v.gost,
  v.length_m,
  'м',
  v.weight_kg,
  v.price_per_ton,
  null,
  null,
  null,
  'in',
  false,
  v.article,
  v.card_title,
  '/products/angle.webp',
  v.sort_order,
  true,
  now()
from (
  values
    (
      'ugolok-stalnoy-art-11555',
      'Уголок равнополочный 75×75×5×12000, ст.сп/пс (ГОСТ 8509-93), Россия',
      '75×75×5×12000 мм',
      75::numeric,
      'Ст3сп/пс',
      'ГОСТ 8509-93',
      12::numeric,
      5.69::numeric,
      4670::numeric,
      '11555',
      'Уголок 75×75×5×12000, Россия',
      1
    ),
    (
      'ugolok-stalnoy-art-17478',
      'Уголок 50×50×4×12000 ГОСТ 8509-93 Россия',
      '50×50×4×12000 мм',
      50::numeric,
      'Ст3сп/пс',
      'ГОСТ 8509-93',
      12::numeric,
      3.01::numeric,
      3860::numeric,
      '17478',
      'Уголок 50×50×4×12000, Россия',
      2
    ),
    (
      'ugolok-stalnoy-art-17477',
      'Уголок 40×40×3 ГОСТ 535-2005 РОССИЯ',
      '40×40×3 мм',
      40::numeric,
      'Ст3',
      'ГОСТ 535-2005',
      6::numeric,
      1.81::numeric,
      3420::numeric,
      '17477',
      'Уголок 40×40×3, Россия',
      3
    ),
    (
      'ugolok-stalnoy-art-05335',
      'Уголок стальной г/к равнополочный 50×50×5 мм',
      '50×50×5 мм',
      50::numeric,
      'Ст3сп/пс',
      'ГОСТ 8509-93',
      6::numeric,
      3.73::numeric,
      3400::numeric,
      '05335',
      'Уголок г/к 50×50×5 мм',
      4
    ),
    (
      'ugolok-stalnoy-art-06428',
      'Уголок стальной г/к равнополочный 32×32×4 мм',
      '32×32×4 мм',
      32::numeric,
      'Ст3сп/пс',
      'ГОСТ 8509-93',
      6::numeric,
      1.88::numeric,
      4090::numeric,
      '06428',
      'Уголок г/к 32×32×4 мм',
      5
    ),
    (
      'ugolok-stalnoy-art-05905',
      'Уголок стальной г/к равнополочный 75×75×6 мм',
      '75×75×6 мм',
      75::numeric,
      'Ст3сп/пс',
      'ГОСТ 8509-93',
      6::numeric,
      6.78::numeric,
      4080::numeric,
      '05905',
      'Уголок г/к 75×75×6 мм',
      6
    ),
    (
      'ugolok-stalnoy-art-05476',
      'Уголок стальной г/к равнополочный 63×63×5 мм',
      '63×63×5 мм',
      63::numeric,
      'Ст3сп/пс',
      'ГОСТ 8509-93',
      6::numeric,
      4.75::numeric,
      4030::numeric,
      '05476',
      'Уголок г/к 63×63×5 мм',
      7
    ),
    (
      'ugolok-stalnoy-art-06559',
      'Уголок стальной г/к равнополочный 25×25×4 мм',
      '25×25×4 мм',
      25::numeric,
      'Ст3сп/пс',
      'ГОСТ 8509-93',
      6::numeric,
      1.44::numeric,
      4300::numeric,
      '06559',
      'Уголок г/к 25×25×4 мм',
      8
    ),
    (
      'ugolok-stalnoy-art-06016',
      'Уголок стальной г/к равнополочный 100×100×7 мм',
      '100×100×7 мм',
      100::numeric,
      'Ст3сп/пс',
      'ГОСТ 8509-93',
      6::numeric,
      10.61::numeric,
      3000::numeric,
      '06016',
      'Уголок г/к 100×100×7 мм',
      9
    ),
    (
      'ugolok-stalnoy-art-09363',
      'Уголок стальной г/к равнополочный 40×40×4 мм',
      '40×40×4 мм',
      40::numeric,
      'Ст3сп/пс',
      'ГОСТ 8509-93',
      6::numeric,
      2.39::numeric,
      3690::numeric,
      '09363',
      'Уголок г/к 40×40×4 мм',
      10
    )
) as v(
  slug,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  weight_kg,
  price_per_ton,
  article,
  card_title,
  sort_order
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  gost = excluded.gost,
  length_m = excluded.length_m,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_ton = excluded.price_per_ton,
  stock = excluded.stock,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
