-- Товары: подкатегория «Лист плоский с полимерным покрытием» (sheet-polymer).
-- Перед запуском: supabase-seed-sheet-subcategories.sql, категория slug listy-stalnye.
-- Цена: 29,33 BYN/м² (price_per_meter); лист 1250×2000 мм = 2,5 м².

insert into public.products (
  slug,
  category_id,
  subcategory_id,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  sale_unit,
  weight_kg,
  price_per_ton,
  price_per_unit,
  price_per_meter,
  meters_per_sale_unit,
  stock,
  popular,
  article,
  card_title,
  image,
  sort_order,
  is_published,
  updated_at
)
select
  v.slug,
  c.id,
  'sheet-polymer',
  v.name,
  v.size,
  v.dimension,
  v.steel,
  v.gost,
  null,
  'лист',
  v.weight_kg,
  null,
  v.price_per_unit,
  v.price_per_meter,
  2.5,
  v.stock,
  false,
  v.article,
  v.card_title,
  '/products/sheet.webp',
  v.sort_order,
  true,
  now()
from public.categories c
cross join (
  values
    (
      'listy-stalnye-polymer-art-10371',
      'Лист плоский синий насыщенный (ПЭП-01-5005-0,45х1250х2000), ООО «Металлопрофиль»',
      '0,45×1250×2000 мм',
      0.45::numeric,
      'ПЭП-01-5005',
      'ТУ производителя',
      8.83::numeric,
      73.33::numeric,
      29.33::numeric,
      'in',
      '10371',
      'Лист плоский синий насыщенный 0,45×1250×2000',
      1
    ),
    (
      'listy-stalnye-polymer-art-09437',
      'Лист плоский красное вино (ПЭП-01-3005-0,45х1250х2000), ООО «Металлопрофиль»',
      '0,45×1250×2000 мм',
      0.45::numeric,
      'ПЭП-01-3005',
      'ТУ производителя',
      8.83::numeric,
      73.33::numeric,
      29.33::numeric,
      'in',
      '09437',
      'Лист плоский красное вино 0,45×1250×2000',
      2
    ),
    (
      'listy-stalnye-polymer-art-09432',
      'Лист плоский коричневый шоколад (ПЭП-01-8017-0,45х1250х2000), ООО «Металлопрофиль»',
      '0,45×1250×2000 мм',
      0.45::numeric,
      'ПЭП-01-8017',
      'ТУ производителя',
      8.83::numeric,
      73.33::numeric,
      29.33::numeric,
      'in',
      '09432',
      'Лист плоский коричневый шоколад 0,45×1250×2000',
      3
    ),
    (
      'listy-stalnye-polymer-art-09430',
      'Лист плоский зеленый мох (ПЭП-01-6005-0,45х1250х2000), ООО «Металлопрофиль»',
      '0,45×1250×2000 мм',
      0.45::numeric,
      'ПЭП-01-6005',
      'ТУ производителя',
      8.83::numeric,
      73.33::numeric,
      29.33::numeric,
      'in',
      '09430',
      'Лист плоский зеленый мох 0,45×1250×2000',
      4
    ),
    (
      'listy-stalnye-polymer-art-09509',
      'Лист плоский белый (ПЭП-01-9003-0,45х1250х2000), ООО «Металлопрофиль»',
      '0,45×1250×2000 мм',
      0.45::numeric,
      'ПЭП-01-9003',
      'ТУ производителя',
      8.83::numeric,
      73.33::numeric,
      29.33::numeric,
      'out',
      '09509',
      'Лист плоский белый 0,45×1250×2000',
      5
    )
) as v(
  slug,
  name,
  size,
  dimension,
  steel,
  gost,
  weight_kg,
  price_per_unit,
  price_per_meter,
  stock,
  article,
  card_title,
  sort_order
)
where c.slug = 'listy-stalnye'
on conflict (slug) do update set
  category_id = excluded.category_id,
  subcategory_id = excluded.subcategory_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  gost = excluded.gost,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_unit = excluded.price_per_unit,
  price_per_meter = excluded.price_per_meter,
  meters_per_sale_unit = excluded.meters_per_sale_unit,
  stock = excluded.stock,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
