-- Категория «Арматура стеклопластиковая» и 7 позиций как на витрине-референсе.
-- Перед запуском: supabase-schema.sql, supabase-admin-rpc.sql
-- Картинка категории: public/products/rebar-catalog/armatura-stekloplastikovaya.png

delete from public.products where slug like 'armatura-kompozitnaya-%';
delete from public.products where slug = 'sterzhen-stekloplastikovyy-ssp-8-50-buhta-50m';

insert into public.categories (
  id, slug, name, menu_name, tagline, description, image, sort_order,
  dimension_label, seo_title, seo_description, is_published, updated_at
) values (
  'fiberglass-rebar',
  'armatura-stekloplastikovaya',
  'Арматура стеклопластиковая',
  'Арматура стеклопластиковая',
  'Бухты и прутки 3 м — цена за метр',
  'Композитная арматура из стеклоровинга: не корродирует, легче стали. Продажа метрами, бухты 25–50 м и прутки по 3 м.',
  '/products/rebar-catalog/armatura-stekloplastikovaya.png',
  3,
  'Диаметр',
  'Арматура стеклопластиковая — купить в Беларуси | Ромедов',
  'Стеклопластиковая арматура в бухтах и прутках, цена за метр, доставка по Беларуси.',
  true,
  now()
)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  menu_name = excluded.menu_name,
  tagline = excluded.tagline,
  description = excluded.description,
  image = excluded.image,
  sort_order = excluded.sort_order,
  dimension_label = excluded.dimension_label,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  is_published = excluded.is_published,
  updated_at = now();

insert into public.products (
  slug, category_id, name, size, dimension, steel, gost, length_m, sale_unit,
  weight_kg, price_per_ton, price_per_unit, price_per_meter, meters_per_sale_unit,
  stock, popular, article, card_title, image, is_published, updated_at
) values
(
  'armatura-stekloplastikovaya-art-15191',
  'fiberglass-rebar',
  'Арматура стеклопластиковая ф. 8 бухта 50 м',
  'Ø8 мм',
  8,
  'АКП',
  'ГОСТ 31938-2012',
  50,
  'боб',
  3.5,
  null,
  59.5,
  1.19,
  50,
  'in', false, '15191',
  'Арматура стеклопластиковая ф. 8 бухта 50 м',
  null,
  true, now()
),
(
  'armatura-stekloplastikovaya-art-15190',
  'fiberglass-rebar',
  'Арматура стеклопластиковая ф.6 бухта 50 м',
  'Ø6 мм',
  6,
  'АКП',
  'ГОСТ 31938-2012',
  50,
  'боб',
  2.5,
  null,
  41.5,
  0.83,
  50,
  'in', false, '15190',
  'Арматура стеклопластиковая ф.6 бухта 50 м',
  null,
  true, now()
),
(
  'armatura-stekloplastikovaya-art-15098',
  'fiberglass-rebar',
  'Арматура стеклопластиковая ф. 10 бухта 50 м',
  'Ø10 мм',
  10,
  'АКП',
  'ГОСТ 31938-2012',
  50,
  'боб',
  6,
  null,
  90,
  1.8,
  50,
  'in', false, '15098',
  'Арматура стеклопластиковая ф. 10 бухта 50 м',
  null,
  true, now()
),
(
  'armatura-stekloplastikovaya-art-15095',
  'fiberglass-rebar',
  'Арматура стеклопластиковая ф. 8 по 3 м',
  'Ø8 мм',
  8,
  'АКП',
  'ГОСТ 31938-2012',
  3,
  'шт',
  0.21,
  null,
  3.57,
  1.19,
  null,
  'in', false, '15095',
  'Арматура стеклопластиковая ф. 8 по 3 м',
  null,
  true, now()
),
(
  'armatura-stekloplastikovaya-art-15094',
  'fiberglass-rebar',
  'Арматура стеклопластиковая ф. 6 бухта 25 м',
  'Ø6 мм',
  6,
  'АКП',
  'ГОСТ 31938-2012',
  25,
  'боб',
  1.25,
  null,
  20.75,
  0.83,
  25,
  'in', false, '15094',
  'Арматура стеклопластиковая ф. 6 бухта 25 м',
  null,
  true, now()
),
(
  'armatura-stekloplastikovaya-art-15093',
  'fiberglass-rebar',
  'Арматура стеклопластиковая ф. 6 по 3 м',
  'Ø6 мм',
  6,
  'АКП',
  'ГОСТ 31938-2012',
  3,
  'шт',
  0.15,
  null,
  2.49,
  0.83,
  null,
  'in', false, '15093',
  'Арматура стеклопластиковая ф. 6 по 3 м',
  null,
  true, now()
),
(
  'armatura-stekloplastikovaya-art-15097',
  'fiberglass-rebar',
  'Арматура стеклопластиковая ф.10 по 3 м',
  'Ø10 мм',
  10,
  'АКП',
  'ГОСТ 31938-2012',
  3,
  'шт',
  0.36,
  null,
  null,
  null,
  null,
  'order', false, '15097',
  'Арматура стеклопластиковая ф.10 по 3 м',
  null,
  true, now()
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  gost = excluded.gost,
  length_m = excluded.length_m,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_ton = excluded.price_per_ton,
  price_per_unit = excluded.price_per_unit,
  price_per_meter = excluded.price_per_meter,
  meters_per_sale_unit = excluded.meters_per_sale_unit,
  stock = excluded.stock,
  popular = excluded.popular,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  is_published = excluded.is_published,
  updated_at = now();
