-- Товары: подкатегория «Трубы стальные водогазопроводные» (pipe-vgp).
-- Перед запуском: supabase-seed-pipe-subcategories.sql.
-- dimension — условный проход Du (мм); weight_kg — масса 1 п.м. (ориентир по ГОСТ 3262-75).

insert into public.products (
  slug,
  category_id,
  subcategory_id,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  sale_unit,
  weight_kg,
  price_per_ton,
  price_per_unit,
  price_per_meter,
  meters_per_sale_unit,
  stock,
  popular,
  article,
  card_title,
  image,
  sort_order,
  is_published,
  updated_at
)
select
  v.slug,
  c.id,
  'pipe-vgp',
  v.name,
  v.size,
  v.dimension,
  v.steel,
  v.gost,
  6::numeric,
  'м',
  v.weight_kg,
  v.price_per_ton,
  null,
  null,
  null,
  'in',
  false,
  v.article,
  v.card_title,
  '/products/pipe-sub/vgp.webp',
  v.sort_order,
  true,
  now()
from public.categories c
cross join (
  values
    (
      'truby-stalnye-vgp-art-05357',
      'Труба чёрная ВГП Ду 32×3,2 ГОСТ 3262-75 (РФ)',
      'Ду 32×3,2 мм',
      32::numeric,
      'Ст3сп',
      'ГОСТ 3262-75',
      2.9::numeric,
      2960::numeric,
      '05357',
      'Труба ВГП Ду 32×3,2, РФ',
      1
    ),
    (
      'truby-stalnye-vgp-art-04935',
      'Труба чёрная ВГП Ду 20×2,8 ГОСТ 3262-75 (РФ)',
      'Ду 20×2,8 мм',
      20::numeric,
      'Ст3сп',
      'ГОСТ 3262-75',
      1.63::numeric,
      2910::numeric,
      '04935',
      'Труба ВГП Ду 20×2,8, РФ',
      2
    ),
    (
      'truby-stalnye-vgp-art-05481',
      'Труба чёрная ВГП Ду 40×3,5 ГОСТ 3262-75 (Россия)',
      'Ду 40×3,5 мм',
      40::numeric,
      'Ст3сп',
      'ГОСТ 3262-75',
      3.55::numeric,
      3330::numeric,
      '05481',
      'Труба ВГП Ду 40×3,5, Россия',
      3
    ),
    (
      'truby-stalnye-vgp-art-05480',
      'Труба чёрная ВГП Ду 25×3,2 мм ГОСТ 3262-75 (Россия)',
      'Ду 25×3,2 мм',
      25::numeric,
      'Ст3сп',
      'ГОСТ 3262-75',
      2.33::numeric,
      2770::numeric,
      '05480',
      'Труба ВГП Ду 25×3,2, Россия',
      4
    ),
    (
      'truby-stalnye-vgp-art-05478',
      'Труба чёрная ВГП Ду 15×2,8 мм ГОСТ 3262-75 (Россия)',
      'Ду 15×2,8 мм',
      15::numeric,
      'Ст3сп',
      'ГОСТ 3262-75',
      1.28::numeric,
      3010::numeric,
      '05478',
      'Труба ВГП Ду 15×2,8, Россия',
      5
    )
) as v(
  slug,
  name,
  size,
  dimension,
  steel,
  gost,
  weight_kg,
  price_per_ton,
  article,
  card_title,
  sort_order
)
where c.slug = 'truby-stalnye'
on conflict (slug) do update set
  category_id = excluded.category_id,
  subcategory_id = excluded.subcategory_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  gost = excluded.gost,
  length_m = excluded.length_m,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_ton = excluded.price_per_ton,
  stock = excluded.stock,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
