-- Категория «Швеллер стальной» + 7 товаров (референс витрины).
-- Перед запуском: supabase-schema.sql, supabase-admin-rpc.sql.
-- weight_kg — масса 1 п.м. по справочнику ГОСТ 8240-97 (ориентир).

insert into public.categories (
  id, slug, name, menu_name, tagline, description, image, sort_order,
  dimension_label, seo_title, seo_description, is_published, updated_at
) values (
  'channel',
  'shveller-stalnoy',
  'Швеллер стальной',
  'Швеллер стальной',
  'П-образный, номера 5–20',
  'Горячекатаный швеллер с параллельными полками по ГОСТ 8240-97. Основа для перекрытий, рам, эстакад и тяжёлых металлоконструкций.',
  '/products/channel.webp',
  7,
  'Номер',
  'Швеллер стальной — купить в Минске и Борисове | Ромедов',
  'Швеллер стальной горячекатаный № 5–20 по ГОСТ 8240-97. Цена за тонну и за метр, наличие на складе, резка, доставка по Беларуси.',
  true,
  now()
)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  menu_name = excluded.menu_name,
  tagline = excluded.tagline,
  description = excluded.description,
  image = excluded.image,
  sort_order = excluded.sort_order,
  dimension_label = excluded.dimension_label,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  is_published = true,
  updated_at = now();

insert into public.products (
  slug,
  category_id,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  sale_unit,
  weight_kg,
  price_per_ton,
  price_per_unit,
  price_per_meter,
  meters_per_sale_unit,
  stock,
  popular,
  article,
  card_title,
  image,
  sort_order,
  is_published,
  updated_at
)
select
  v.slug,
  'channel',
  v.name,
  v.size,
  v.dimension,
  v.steel,
  v.gost,
  v.length_m,
  'м',
  v.weight_kg,
  v.price_per_ton,
  null,
  null,
  null,
  v.stock,
  false,
  v.article,
  v.card_title,
  '/products/channel.webp',
  v.sort_order,
  true,
  now()
from (
  values
    (
      'shveller-stalnoy-art-05902',
      'Швеллер стальной г/к 10П ст3сп5 ГОСТ 8240-97, Россия',
      '№ 10П',
      10::numeric,
      'Ст3сп5',
      'ГОСТ 8240-97',
      6::numeric,
      8.59::numeric,
      2667.7::numeric,
      'in',
      '05902',
      'Швеллер г/к 10П, Россия',
      1
    ),
    (
      'shveller-stalnoy-art-08673',
      'Швеллер стальной 18П, ГОСТ 27772-2021, Россия',
      '№ 18П',
      18::numeric,
      'Ст3сп',
      'ГОСТ 27772-2021',
      6::numeric,
      18.4::numeric,
      4080::numeric,
      'in',
      '08673',
      'Швеллер 18П, Россия',
      2
    ),
    (
      'shveller-stalnoy-art-09365',
      'Швеллер стальной г/к 16П',
      '№ 16П',
      16::numeric,
      'Ст3сп',
      'ГОСТ 8240-97',
      6::numeric,
      15.9::numeric,
      4330::numeric,
      'in',
      '09365',
      'Швеллер г/к 16П',
      3
    ),
    (
      'shveller-stalnoy-art-09231',
      'Швеллер г/к 12П×12000-МД Ст3сп-5 (Россия)',
      '№ 12П×12000 мм',
      12::numeric,
      'Ст3сп5',
      'ГОСТ 8240-97',
      12::numeric,
      10.4::numeric,
      2719.2::numeric,
      'in',
      '09231',
      'Швеллер г/к 12П×12 м',
      4
    ),
    (
      'shveller-stalnoy-art-08493',
      'Швеллер стальной г/к 8',
      '№ 8',
      8::numeric,
      'Ст3сп',
      'ГОСТ 8240-97',
      6::numeric,
      7.05::numeric,
      3090::numeric,
      'in',
      '08493',
      'Швеллер г/к 8',
      5
    ),
    (
      'shveller-stalnoy-art-13070',
      'Швеллер стальной г/к 20П',
      '№ 20П',
      20::numeric,
      'Ст3сп',
      'ГОСТ 8240-97',
      6::numeric,
      21::numeric,
      5718.54::numeric,
      'in',
      '13070',
      'Швеллер г/к 20П',
      6
    ),
    (
      'shveller-stalnoy-art-11210',
      'Швеллер стальной г/к 6,5',
      '№ 6,5',
      6.5::numeric,
      'Ст3сп',
      'ГОСТ 8240-97',
      6::numeric,
      5.98::numeric,
      null::numeric,
      'out',
      '11210',
      'Швеллер г/к 6,5',
      7
    )
) as v(
  slug,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  weight_kg,
  price_per_ton,
  stock,
  article,
  card_title,
  sort_order
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  gost = excluded.gost,
  length_m = excluded.length_m,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_ton = excluded.price_per_ton,
  stock = excluded.stock,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
