-- Товары: подкатегория «Лист стальной холоднокатаный» (sheet-hk).
-- Перед запуском: supabase-seed-sheet-subcategories.sql, категория slug listy-stalnye.

insert into public.products (
  slug,
  category_id,
  subcategory_id,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  sale_unit,
  weight_kg,
  price_per_ton,
  price_per_unit,
  price_per_meter,
  meters_per_sale_unit,
  stock,
  popular,
  article,
  card_title,
  image,
  sort_order,
  is_published,
  updated_at
)
select
  v.slug,
  c.id,
  'sheet-hk',
  v.name,
  v.size,
  v.dimension,
  v.steel,
  v.gost,
  null,
  'лист',
  v.weight_kg,
  v.price_per_ton,
  null,
  null,
  null,
  v.stock,
  false,
  v.article,
  v.card_title,
  '/products/sheet.webp',
  v.sort_order,
  true,
  now()
from public.categories c
cross join (
  values
    (
      'listy-stalnye-hk-art-10537',
      'Лист х/к 1,2×1250×2500, РФ',
      '1,2×1250×2500 мм',
      1.2::numeric,
      'Ст3сп',
      'ГОСТ 19904-90',
      29.44::numeric,
      3090::numeric,
      'in',
      '10537',
      'Лист х/к 1,2×1250×2500',
      1
    ),
    (
      'listy-stalnye-hk-art-12241',
      'Лист холоднокатаный 1×1250×2500 мм',
      '1×1250×2500 мм',
      1::numeric,
      'Ст3сп',
      'ГОСТ 19904-90',
      24.53::numeric,
      3370::numeric,
      'in',
      '12241',
      'Лист х/к 1×1250×2500',
      2
    ),
    (
      'listy-stalnye-hk-art-09264',
      'Лист холоднокатаный 1,5×1250×2500 мм',
      '1,5×1250×2500 мм',
      1.5::numeric,
      'Ст3сп',
      'ГОСТ 19904-90',
      36.8::numeric,
      3310::numeric,
      'in',
      '09264',
      'Лист х/к 1,5×1250×2500',
      3
    ),
    (
      'listy-stalnye-hk-art-09262',
      'Лист холоднокатаный 0,8×1250×2500 мм',
      '0,8×1250×2500 мм',
      0.8::numeric,
      'Ст3сп',
      'ГОСТ 19904-90',
      19.63::numeric,
      3110::numeric,
      'in',
      '09262',
      'Лист х/к 0,8×1250×2500',
      4
    )
) as v(
  slug,
  name,
  size,
  dimension,
  steel,
  gost,
  weight_kg,
  price_per_ton,
  stock,
  article,
  card_title,
  sort_order
)
where c.slug = 'listy-stalnye'
on conflict (slug) do update set
  category_id = excluded.category_id,
  subcategory_id = excluded.subcategory_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  gost = excluded.gost,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_ton = excluded.price_per_ton,
  stock = excluded.stock,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
