-- Товар: подкатегория «Лист рифлёный стальной» (sheet-rif).
-- Перед запуском: supabase-seed-sheet-subcategories.sql, категория slug listy-stalnye.

insert into public.products (
  slug,
  category_id,
  subcategory_id,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  sale_unit,
  weight_kg,
  price_per_ton,
  price_per_unit,
  price_per_meter,
  meters_per_sale_unit,
  stock,
  popular,
  article,
  card_title,
  image,
  sort_order,
  is_published,
  updated_at
)
select
  'listy-stalnye-rif-art-09889',
  c.id,
  'sheet-rif',
  'Лист рифленый стальной чечевица 4×1500×6000',
  '4×1500×6000 мм',
  4::numeric,
  'Ст3сп',
  'ГОСТ 8568-77',
  null,
  'лист',
  282.6::numeric,
  2970::numeric,
  null,
  null,
  null,
  'in',
  false,
  '09889',
  'Лист рифлёный чечевица 4×1500×6000',
  '/products/sheet.webp',
  1,
  true,
  now()
from public.categories c
where c.slug = 'listy-stalnye'
on conflict (slug) do update set
  category_id = excluded.category_id,
  subcategory_id = excluded.subcategory_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  gost = excluded.gost,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_ton = excluded.price_per_ton,
  stock = excluded.stock,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
