-- Товары: подкатегория «Лист стальной оцинкованный» (sheet-zn).
-- Перед запуском: supabase-seed-sheet-subcategories.sql, категория slug listy-stalnye.
-- Цена: BYN/м² (price_per_meter); площадь листа в meters_per_sale_unit.

insert into public.products (
  slug,
  category_id,
  subcategory_id,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  sale_unit,
  weight_kg,
  price_per_ton,
  price_per_unit,
  price_per_meter,
  meters_per_sale_unit,
  stock,
  popular,
  article,
  card_title,
  image,
  sort_order,
  is_published,
  updated_at
)
select
  v.slug,
  c.id,
  'sheet-zn',
  v.name,
  v.size,
  v.dimension,
  v.steel,
  v.gost,
  null,
  'лист',
  v.weight_kg,
  null,
  v.price_per_unit,
  v.price_per_meter,
  v.area_m2,
  v.stock,
  false,
  v.article,
  v.card_title,
  '/products/sheet.webp',
  v.sort_order,
  true,
  now()
from public.categories c
cross join (
  values
    (
      'listy-stalnye-zn-art-12387',
      'Лист стальной оцинкованный 0,55×1250×2500',
      '0,55×1250×2500 мм',
      0.55::numeric,
      'оцинкованная сталь',
      'ГОСТ 52246-2016',
      13.48::numeric,
      65.63::numeric,
      21::numeric,
      3.125::numeric,
      'in',
      '12387',
      'Лист оцинкованный 0,55×1250×2500',
      1
    ),
    (
      'listy-stalnye-zn-art-12386',
      'Лист стальной оцинкованный 0,7×1250×2500',
      '0,7×1250×2500 мм',
      0.7::numeric,
      'оцинкованная сталь',
      'ГОСТ 52246-2016',
      17.16::numeric,
      78.31::numeric,
      25.06::numeric,
      3.125::numeric,
      'in',
      '12386',
      'Лист оцинкованный 0,7×1250×2500',
      2
    ),
    (
      'listy-stalnye-zn-art-12347',
      'Лист стальной оцинкованный 0,45×1250×2000',
      '0,45×1250×2000 мм',
      0.45::numeric,
      'оцинкованная сталь',
      'ГОСТ 52246-2016',
      8.83::numeric,
      43.65::numeric,
      17.46::numeric,
      2.5::numeric,
      'in',
      '12347',
      'Лист оцинкованный 0,45×1250×2000',
      3
    )
) as v(
  slug,
  name,
  size,
  dimension,
  steel,
  gost,
  weight_kg,
  price_per_unit,
  price_per_meter,
  area_m2,
  stock,
  article,
  card_title,
  sort_order
)
where c.slug = 'listy-stalnye'
on conflict (slug) do update set
  category_id = excluded.category_id,
  subcategory_id = excluded.subcategory_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  gost = excluded.gost,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_unit = excluded.price_per_unit,
  price_per_meter = excluded.price_per_meter,
  meters_per_sale_unit = excluded.meters_per_sale_unit,
  stock = excluded.stock,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
