-- Товары: подкатегория «Заглушки на профильные трубы» (supplies-caps).
-- Перед запуском: supabase-seed-supplies-subcategories.sql.
-- dimension — большая сторона сечения (мм) для фильтра «Типоразмер».

insert into public.products (
  slug,
  category_id,
  subcategory_id,
  name,
  size,
  dimension,
  steel,
  gost,
  length_m,
  sale_unit,
  weight_kg,
  price_per_ton,
  price_per_unit,
  price_per_meter,
  meters_per_sale_unit,
  stock,
  popular,
  article,
  card_title,
  image,
  sort_order,
  is_published,
  updated_at
)
select
  v.slug,
  c.id,
  'supplies-caps',
  v.name,
  v.size,
  v.dimension,
  v.steel,
  '',
  null,
  'шт',
  v.weight_kg,
  null,
  v.price_per_unit,
  null,
  null,
  v.stock,
  false,
  v.article,
  v.card_title,
  '/products/supplies.webp',
  v.sort_order,
  true,
  now()
from public.categories c
cross join (
  values
    (
      'soputstvuyushchie-art-16790',
      'Заглушка квадратная внутр. 30×30 универсальная',
      '30×30 мм',
      30::numeric,
      'пластик',
      0.02::numeric,
      0.8::numeric,
      'in',
      '16790',
      'Заглушка внутр. 30×30',
      1
    ),
    (
      'soputstvuyushchie-art-16791',
      'Заглушка квадратная внутр. 20×20',
      '20×20 мм',
      20::numeric,
      'пластик',
      0.02::numeric,
      null::numeric,
      'out',
      '16791',
      'Заглушка внутр. 20×20',
      2
    ),
    (
      'soputstvuyushchie-art-12417',
      'Заглушка пластиковая квадратная 120×120 мм, Россия',
      '120×120 мм',
      120::numeric,
      'пластик',
      0.08::numeric,
      10.8::numeric,
      'in',
      '12417',
      'Заглушка 120×120, Россия',
      3
    ),
    (
      'soputstvuyushchie-art-12416',
      'Заглушка пластиковая прямоугольная 20×40 мм, Россия',
      '20×40 мм',
      40::numeric,
      'пластик',
      0.02::numeric,
      0.5::numeric,
      'in',
      '12416',
      'Заглушка 20×40, Россия',
      4
    ),
    (
      'soputstvuyushchie-art-12415',
      'Заглушка пластиковая прямоугольная 40×80 мм, Россия',
      '40×80 мм',
      80::numeric,
      'пластик',
      0.03::numeric,
      1::numeric,
      'in',
      '12415',
      'Заглушка 40×80, Россия',
      5
    ),
    (
      'soputstvuyushchie-art-11676',
      'Заглушка пластиковая квадратная 40×40 мм, Россия',
      '40×40 мм',
      40::numeric,
      'пластик',
      0.02::numeric,
      0.8::numeric,
      'in',
      '11676',
      'Заглушка 40×40, Россия',
      6
    ),
    (
      'soputstvuyushchie-art-11675',
      'Заглушка пластиковая квадратная 50×50 мм, Россия',
      '50×50 мм',
      50::numeric,
      'пластик',
      0.03::numeric,
      0.85::numeric,
      'in',
      '11675',
      'Заглушка 50×50, Россия',
      7
    ),
    (
      'soputstvuyushchie-art-11674',
      'Заглушка пластиковая квадратная 100×100 мм, Россия',
      '100×100 мм',
      100::numeric,
      'пластик',
      0.06::numeric,
      3.1::numeric,
      'in',
      '11674',
      'Заглушка 100×100, Россия',
      8
    ),
    (
      'soputstvuyushchie-art-11673',
      'Заглушка пластиковая прямоугольная 60×80 мм, Россия',
      '60×80 мм',
      80::numeric,
      'пластик',
      0.04::numeric,
      1.5::numeric,
      'in',
      '11673',
      'Заглушка 60×80, Россия',
      9
    ),
    (
      'soputstvuyushchie-art-11672',
      'Заглушка пластиковая квадратная 80×80 мм, Россия',
      '80×80 мм',
      80::numeric,
      'пластик',
      0.05::numeric,
      2::numeric,
      'in',
      '11672',
      'Заглушка 80×80, Россия',
      10
    ),
    (
      'soputstvuyushchie-art-11671',
      'Заглушка пластиковая квадратная 60×60 мм, Россия',
      '60×60 мм',
      60::numeric,
      'пластик',
      0.04::numeric,
      1.2::numeric,
      'in',
      '11671',
      'Заглушка 60×60, Россия',
      11
    ),
    (
      'soputstvuyushchie-art-11670',
      'Заглушка пластиковая прямоугольная 40×60 мм, Россия',
      '40×60 мм',
      60::numeric,
      'пластик',
      0.03::numeric,
      1.2::numeric,
      'in',
      '11670',
      'Заглушка 40×60, Россия',
      12
    )
) as v(
  slug,
  name,
  size,
  dimension,
  steel,
  weight_kg,
  price_per_unit,
  stock,
  article,
  card_title,
  sort_order
)
where c.slug = 'soputstvuyushchie-tovary'
on conflict (slug) do update set
  category_id = excluded.category_id,
  subcategory_id = excluded.subcategory_id,
  name = excluded.name,
  size = excluded.size,
  dimension = excluded.dimension,
  steel = excluded.steel,
  sale_unit = excluded.sale_unit,
  weight_kg = excluded.weight_kg,
  price_per_unit = excluded.price_per_unit,
  stock = excluded.stock,
  article = excluded.article,
  card_title = excluded.card_title,
  image = excluded.image,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  updated_at = now();
