/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogCategoryRouteImport } from './routes/catalog.$category'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogCategoryRoute = CatalogCategoryRouteImport.update({
  id: '/catalog/$category',
  path: '/catalog/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/search': typeof SearchRoute
  '/catalog/$category': typeof CatalogCategoryRoute
  '/product/$slug': typeof ProductSlugRoute
  '/catalog/': typeof CatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/search': typeof SearchRoute
  '/catalog/$category': typeof CatalogCategoryRoute
  '/product/$slug': typeof ProductSlugRoute
  '/catalog': typeof CatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/search': typeof SearchRoute
  '/catalog/$category': typeof CatalogCategoryRoute
  '/product/$slug': typeof ProductSlugRoute
  '/catalog/': typeof CatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contacts'
    | '/delivery'
    | '/search'
    | '/catalog/$category'
    | '/product/$slug'
    | '/catalog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contacts'
    | '/delivery'
    | '/search'
    | '/catalog/$category'
    | '/product/$slug'
    | '/catalog'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/contacts'
    | '/delivery'
    | '/search'
    | '/catalog/$category'
    | '/product/$slug'
    | '/catalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactsRoute: typeof ContactsRoute
  DeliveryRoute: typeof DeliveryRoute
  SearchRoute: typeof SearchRoute
  CatalogCategoryRoute: typeof CatalogCategoryRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$category': {
      id: '/catalog/$category'
      path: '/catalog/$category'
      fullPath: '/catalog/$category'
      preLoaderRoute: typeof CatalogCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactsRoute: ContactsRoute,
  DeliveryRoute: DeliveryRoute,
  SearchRoute: SearchRoute,
  CatalogCategoryRoute: CatalogCategoryRoute,
  ProductSlugRoute: ProductSlugRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
